export const APP_CONFIG = {
  // 分页配置
  PAGE_SIZE_DEFAULT: 10,
  PAGE_SIZE_GRID: 12,

  // 上传限制
  MAX_FILE_SIZE_MB: 50,
  MAX_FILE_SIZE_BYTES: 50 * 1024 * 1024,
  MAX_UPLOAD_COUNT: 10,
  RECENT_UPLOADS_LIMIT: 3,

  // 缓存配置
  IMAGE_CACHE_DURATION_MS: 5 * 60 * 1000, // 5分钟

  // OSS 配置
  OSS_LIST_MAX_KEYS: 100,
  OSS_LIST_MAX_LOOPS: 10,
  OSS_TEST_MAX_KEYS: 1,
  OSS_DEFAULT_PAGE_SIZE: 50,

  // 图片压缩
  COMPRESSION: {
    MAX_SIZE_MB: 1,
    MAX_WIDTH_OR_HEIGHT: 1920,
    INITIAL_QUALITY: 0.6,
  },

  // Toast 显示时长
  TOAST_DURATION_SUCCESS: 2000,
  TOAST_DURATION_ERROR: 3000,

  // 文件单位
  BYTES_PER_KB: 1024,
} as const;
